ecommerce/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
# for the static files
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Url for products
     url(r'^$', 'products.views.home', name='home'),
     url(r'^products/$', 'products.views.all', name='products'),
     url(r'^s/$', 'products.views.search', name='search'),
     url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single_product'),

     #urls that are for the  cart
     url(r'^cart/$', 'carts.views.view', name='cart'),
     url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
     url(r'^cart/(?P<slug>[\w-]+)/$', 'carts.views.add_to_cart', name='add_to_cart'),

        #urls that are for orders
     url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
     url(r'^orders/$', 'orders.views.orders', name='user_orders'),


     url(r'^admin/', include(admin.site.urls)),
     url(r'^accounts/logout/$','accounts.views.logout_view', name='auth_logout'),
     url(r'^accounts/login/$','accounts.views.login_view', name='auth_login'),
     url(r'^accounts/register/$','accounts.views.registration_view', name='auth_register'),
     url(r'^accounts/activate/(?P<activationkey>\w+)/$', 'accounts.views.activation_view', name='activation_view'),


)
# if the Debug settings is true then it will serve the static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class Product(models.Model):
    ##all of the item characteristics that we will add into the db##
    title = models.CharField(max_length=140, blank= False)
    description= models.TextField(max_length=500, null=True, blank=True)
    price = models.DecimalField(max_digits= 100, default=29.99, decimal_places= 2)
    sale_price = models.DecimalField(max_digits= 100, null=True, blank=True, decimal_places= 2)
    slug = models.SlugField(unique=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.title


    class Meta:
        unique_together = ("title", "slug")

    def get_price(self):
        return self.price

    def get_absolute_url(self):
        return reverse("single_product", kwargs={"slug":self.slug})
        #return "/products/%s/"%(self.slug)

## the upcoming section is made possible after installing pillow to python. **check that//
## you have pillow or use pip to install it.
## creating an image field.
class ProductImage(models.Model):
    product= models.ForeignKey(Product)
    image = models.ImageField(upload_to= 'products/images/')
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.product.title
#setting up the variations manager for variations
# These are the models that are dedicated to all the different variations that a product would be

class VariationManager(models.Manager):
    #setting the active to true
    def all(self):
        return super(VariationManager, self).filter(active=True)

    def sizes(self):
        return self.all().filter(category="size")

    def color(self):
        return self.all().filter(category="color")

    def package(self):
        return self.all().filter(category="package")


# the tuples of different categories in the product variations.
VAR_CATEGORIES = (
    ("size", "size"),
    ("color", "color"),
    ("package", "package")

)
# creating the models for the product variations
class Variation(models.Model):
    # linking up the product variation to the product itself
    product= models.ForeignKey(Product)

    # all the categories expressed within the tuple VAR_CATEGORIES now placed in the model
    category= models.CharField(max_length=120, choices=VAR_CATEGORIES, default="color")

    # linking up the product variation to the product image.
    image= models.ForeignKey(ProductImage, null=True, blank=True)

    title = models.CharField(max_length=120)
    price= models.DecimalField(max_digits=100, decimal_places=2,null=True, blank=True)
    active = models.BooleanField(default=True)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    #setting up the variations manager so that the variations can work
    objects= VariationManager()


    def __unicode__(self):
       return self.title

products/views.py
from django.shortcuts import render, Http404

from .models import Product, ProductImage
from marketing.models import MarketingMessage

# Create your views here.

#home page with all the products that the admin will add.
def home(request):
    products = Product.objects.all()
    # marketing_message = MarketingMessage.objects.all()[0]
    context = {'products':products}

    return render(request, "products/home.html", context)

#the search button queries the results of what you search.
def search(request):
    try:
       q = request.GET.get('q')
    except:
        q = None
    if q:
        products =Product.objects.filter(title__icontains=q)
        context = {"query":q, 'products':products}
        template = "products/results.html"
    else:
        context = {}
        template = "products/home.html"
    return render(request, template, context)


def all(request):
    # del request.session['marketing_message']
    #grabbing all the objects in the products module by models.py
    products = Product.objects.all()
    context = {'products':products}
    return render(request, "products/all.html", context)


def single(request, slug):

    try:
        #grabbing all the objects in the products module by models.py
        product = Product.objects.get(slug=slug)
        #images = product.productimages_set.all()
        images =ProductImage.objects.filter(product=product)
        # products = Product.objects.all()
        context = {'product':product, "images": images}
        return render(request, "products/single.html", context)
    except:
        raise Http404

templates/products/all.html
{% extends 'base.html' %}


{% load staticfiles %}

{% block head_title %}
Products || 
{% endblock %}

{% block styles %}
.jumbotron {
	/*color: red;*/
}
{% endblock %}


{# Comments here #}


{% block content %}




<div class='row'>
<!-- have six products displayed in a row-->

{% for product in products %}
		<div class='col-sm-2'>



			<div class="thumbnail">
					{% if product.productimage_set.all %}

							{% for item in product.productimage_set.all %}

							{% if item.featured %}
							<div style="width:100px;margin:0 auto;">

								<a href='{{ product.get_absolute_url }}'>
									<div class='background_img_thumb' style="height:100px;background-image: url('{{ MEDIA_URL }}{{ item.image }}');"></div>
								</a>
							</div>
							<!-- <img class='img-responsive' src="{{ MEDIA_URL }}{{ item.image }}" /> -->
							{% endif %}
							 


							{% endfor %}

					{% else %}
					<div style="width:100px;margin:0 auto;">

								<a href='{{ product.get_absolute_url }}'>
									<div class='background_img_thumb' style="height:100px;"></div>
								</a>
							</div>
					{% endif %}

					<div class="caption">
					<a href='{{ product.get_absolute_url }}'> <h3>{{ product.title }}</h3></a>
					<p>{{ product.description|truncatewords:10}}</p>
					<p><a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">View</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
					</div>
		   	 </div>


		</div>

{% cycle "" "" "" "" "" "</div><br/><hr/><div class='row'>" %}
{% endfor %}

</div>

{% endblock %}

templates/products/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}
Welcome to
{% endblock %}

{% block styles %}
.jumbotron {
	/*color: red;*/
}
{% endblock %}

{% block jquery %}
//alert("welcome!");
{% endblock%}

{# Comments here #}


{% block jumbotron2 %}
  <div class="container">

			<!-- Main component for a primary marketing message or call to action -->
			<div class="jumbotron">
			<h1> Hello {{ username_is }}</h1>
			<p>This example is a quick exercise to illustrate how the default, static and fixed to top navbar work. It includes the responsive CSS and HTML, so it also adapts to your viewport and device.</p>
			<p>To see the difference between static and fixed top navbars, just scroll.</p>
			<p>
			<a class="btn btn-lg btn-primary" href="../../components/#navbar" role="button">View navbar docs &raquo;</a>
			</p>
			</div>
  </div>
{% endblock %}

{% block content %}

<div class='row'>

{% for product in products %}
		<div class='col-sm-4'>



			<div class="thumbnail">
					{% if product.productimage_set.all %}

							{% for item in product.productimage_set.all %}

							{% if item.featured %}
							<div style="
							width:250px;
							height:200px;
							margin: 0 auto;">
							<a href='{{ product.get_absolute_url }}'>
							<!--/*background-color:lightslategrey;*/-->
							<div class='background_img_thumb', style="background-image:url('{{ MEDIA_URL }}{{ item.image }}');">
							</div>
							</a>
							</div>
							<!--<img class='img-responsive' src="{{ MEDIA_URL }}{{ item.image }}" />-->
							{% endif %}
							 


							{% endfor %}

					{% else %}
					<img class='img-responsive' src='{% static "img/placeholder.svg" %}' />
					{% endif %}

					<div class="caption">
					<a href='{{ product.get_absolute_url }}'> <h3>{{ product.title }}</h3></a>
					<p>{{ product.description|truncatewords:15}}</p>
					<p><a href="{{ product.get_absolute_url }}" class="btn btn-primary" role="button">View</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
					</div>
		   	 </div>


		</div>

{% cycle "" "" "</div><br/><hr/><div class='row'>" %}
{% endfor %}

</div>

{% endblock %}

templates/products/results.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

<h1>Searched for: {{ query }}</h1>

<!--create a table to show the search results-->
<table class="table">
    <!--table headers-->
<thead>
<th></th>
<th>Product</th>
</thead>
<tbody>
{% for product in products %}
    <tr>
    <!--image in search results-->
    <td style="
    width: 160px;
    height:160px;">
    {% if product.productimage_set.all %}
        {% for item in product.productimage_set.all %}
        <!-- if the image is has been featured as the main image-->
            {% if item.featured %}

        <!--<div style="-->
        <!--width:100%;-->
        <!--height: 100%;-->
        <!--background-image:url('{{ MEDIA_URL }}{{ item.image }}');-->
        <!--background-size: cover;-->
        <!--background-repeat: no-repeat;-->
        <!--background-position: center">-->



        <a href='{{ product.get_absolute_url }}'>
        <!-- hard coding the height and width so that we can click the image to take to the product-->
        <div class="background_img_thumb", style="height:160px; width:160px; background-image:url('{{ MEDIA_URL }}{{ item.image }}');">
        </div>
        </a>
        </div>

            {% endif %}
        {% endfor %}
    {%else%}
        <!-- if there is no image attached with the product-->
        <a href='{{ product.get_absolute_url }}'>
        <div class="background_img_thumb style",style="height:160px;"></div>
        </a>
    <!--<div style="-->
        <!--width:100%;-->
        <!--height: 100%;-->
        <!--background-image: url('{% static 'img/placeholder.svg'%}');-->
        <!--background-size: cover;-->
        <!--background-repeat: no-repeat;-->
        <!--background-position: center">-->
    <!--</div>-->
    {%endif%}

    </td>
    <td>
     <!-- get the products in the table in the search query-->
        <a href="{{product.get_absolute_url}}">
         {{ product }}</a>
    </td>
    </tr>
{% endfor %}
</tbody>
</table>
<!--end of image in search results-->


{% endblock %}

templates/products/single.html
{% extends 'base.html' %}

<div class="page-header">
  <h1>{{ product.title }}</h1>
</div>

{% block content %}


<div class='row'>
	<div class='col-sm-4'>
	{% for img in images %}

		{% if img.featured %}
		<div class="col-xs-12">
			<img class='img-responsive' src="{{ MEDIA_URL }}{{ img.image }}" />
		<hr/>
		</div>
		{% endif %}
			{% endfor %}
	{% for img in images %}
		{% if not img.featured %}
		<div class="col-xs-6">
	    <a href="#" class="thumbnail">
	      <img class='img-responsive' src="{{ MEDIA_URL }}{{ img.image }}">
	    </a>
	  	</div>

		{% endif %}
								 
	{% endfor %}
	</div>
	<div class='col-sm-8'>
		<div class='col-sm-8 pull-left'>
		 <h1>{{ product.title }}


		 </h1>
		</div>
		<!--cart-->

		<div class='col-sm-4 pull-right'>
			<form class='form pull-right' method='POST' action='{% url "add_to_cart" product.slug %}'>{% csrf_token %}
			<input class="btn btn-default btn-group-justified" button style="background-color:lightgrey" type='submit' value='Add to cart'/>
			<input class="form-control" name='qty' type='number' value='1'/>
			<!--<input class="form-control" name='attr' type='text' placeholder='color' />-->
			<!--drop down menu in the color drop down above-->

			<!--<select class="form-control"name="color">-->
				<!--<option value="red">Red</option>-->
				<!--<option value="blue" >Blue</option>-->
				<!--<option value="green">Green</option>-->
				<!--<option value="orange">Orange</option>-->
				<!--<option value="black">Black</option>-->
			<!--</select>-->

				<!-- change in variations including size, color etc.//
				drop down menu in single products besides item number -->
			{% if product.variation_set.all %}

				<!-- variation for size -->
			{%  if product.variation_set.sizes %}
			<select class="form-control"name="size">
			{% for item in product.variation_set.sizes  %}
				<option value='{{item.title|lower}}'>{{item.title|capfirst}}</option>
			{% endfor %}
			</select>
			{% endif %}

					<!-- variation for color -->
			{%  if product.variation_set.color %}
			<select class="form-control"name="color">
			{% for item in product.variation_set.color  %}
			<option value='{{item}}'>{{item.title|capfirst}}</option>
			{% endfor %}
			</select>
			{% endif %}


			{% endif %}
			</form>
		</div>

		<div class='col-sm-12'>
			<hr/>
			 Price: {{ product.price }} <br/>
			 Shipping: Free with $25+ purchase.
			 <hr/>
		</div>
		<div class='col-sm-12'>
			{{ product.description|linebreaks }}
		</div>
	</div>
</div>
{% endblock %}